ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Models/Cliente.cs
namespace WebApplication8.Models
{
    public class Cliente : Entity
    {
        public string Name { get;  private set; }

        public string DocumentoI { get; private set; }

        public string TipoCliente { get; private set; }

        public Guid SupermercadoId { get; private set; }



        public Supermercado Supermercado { get; private set; }

        private Cliente() : base()
        {

        }

        private Cliente( Guid id, string name, string documentoI, string tipocliente, Guid supermercadoId) : base(id)
            
        {
            Name = name;
            DocumentoI = documentoI;
            TipoCliente = tipocliente;
            SupermercadoId = supermercadoId;
        }

        public static Cliente Build(Guid id, string name, string documentoI, string tipocliente, Guid supermercadoId)
        {
            return new Cliente(id, name, documentoI, tipocliente, supermercadoId);
        }

        internal static object Build(Func<Guid> newGuid, string name, string documentoI, string tipocliente, Guid supermercadoId)
        {
            throw new NotImplementedException();
        }
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Models/Entity.cs
namespace WebApplication8.Models
{
    public abstract class Entity
    {
        public Guid Id { get; protected set; }

        protected Entity()
        {

        }

        protected Entity(Guid id)
        {
            Id = id;
        }
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Models/ErrorViewModel.cs
namespace WebApplication8.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Models/Supermercado.cs
namespace WebApplication8.Models
{
    public class Supermercado : Entity
    {
        public string NameSuper { get; private set; }

        public string Direccion { get; private set; }

        public Boolean Autoservicio { get; private set; }

        public List<Cliente> Clientes { get; private set; }
        public static bool IsValid { get; private set; }

        private Supermercado() : base()
        {

        }

        private Supermercado(Guid id, string namesuper, string direccion, Boolean autoservicio) : base(id)
        {
            NameSuper = namesuper;
            Direccion = direccion;
            Autoservicio = autoservicio;
            List<Cliente> Clientes = new List<Cliente>();
        }

        public static Supermercado Build(Guid id, string namesuper, string direccion, Boolean autoservicio)
        {
            return new Supermercado(id, namesuper, direccion, autoservicio);
        }
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Models/Vendedor.cs
namespace WebApplication8.Models
{
    public class Vendedor : Entity
    {
        public int CodigoVendedor { get; private set; }

        public string Cargo { get; private set; }

        public string Ventas { get; private set; }

        public Guid ClienteId { get; private set; }

        public Cliente Cliente { get; private set; }

        private Vendedor() : base()
        {

        }

        private Vendedor(Guid id, int codigoVendedor, string cargo, string ventas, Guid clienteId) : base(id)
        {
            CodigoVendedor = codigoVendedor;
            Cargo = cargo;
            Ventas = ventas;
            ClienteId = clienteId;
        }

        public static Vendedor Build(Guid id, int codigoVendedor, string cargo, string ventas, Guid clienteId)
        {
            return new Vendedor(id, codigoVendedor, cargo, ventas, clienteId);
        }
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication8.Models;
using WebApplication8.Services;


namespace WebApplication8.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ClientesServices clientesServices;

        public ClienteController(ClientesServices clientesServices)
        {
            this.clientesServices = clientesServices;
        }


        [HttpGet]
        public async Task<IActionResult> IndexCliente()
        {
            var clientes = await clientesServices.GetAllClientes();

            return View(clientes);
        }

        [HttpPost]
        public async Task<IActionResult>Crear(string name, string documentoI, string tipocliente, Guid supermercadoId)
        {
            var cliente = Cliente.Build(Guid.NewGuid, name, documentoI, tipocliente, supermercadoId);

            await this.clientesServices.Crear(cliente);

            return View();
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }










    }







}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication8.Models;

namespace WebApplication8.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Controllers/SupermercadoController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication8.Models;
using WebApplication8.Services;
using WebApplication8.Data;

namespace WebApplication8.Controllers
{
    public class SupermercadoController : Controller
    {
        private readonly SupermercadoServices supermercadoServices;

        public SupermercadoController(SupermercadoServices supermercadoServices)
        {
            this.supermercadoServices = supermercadoServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var supermercados = await supermercadoServices.GetAllSupermercados();

            return View(supermercados);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }
  
        [HttpPost]
        public async Task<IActionResult> Crear(string namesuper, string direccion, Boolean autoservicio)
        {
            Supermercado supermercado = Supermercado.Build(Guid.NewGuid(), namesuper, direccion, autoservicio);

            await this.supermercadoServices.Crear(supermercado);

            return View();
        }

        [HttpGet]
        public IActionResult Modificar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Modificar(string namesuper, string direccion, Boolean autoservicio)
        {
            Supermercado supermercado = Supermercado.Build(Guid.NewGuid(), namesuper, direccion, autoservicio);

            await this.supermercadoServices.Modificar(supermercado);

            return View();
        }

    }
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Cliente/Index.cshtml
@using WebApplication8.Models;
@model List<Cliente>


@{
    ViewData["title"] = "Index";
}

@if (Model.Count !=0)

{
    <table class="table table-info">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">DocumentoI</th>
                <th scope="col">TipoCliente</th>
                <th scope="col">SupermercadoId</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in Model)
            {
                <tr>
                    <td>@client.Id</td>
                    <td>@client.Name</td>
                    <td>@client.DocumentoI</td>
                    <td>@client.TipoCliente</td>
                    <td>@client.SupermercadoId</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="card">
        <div class="card-body">
            No hay datos del cliente
        </div>
    </div>
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="Title">Bienvenidos</h1>
    <p class="Subtitle">A los mejores SuperMarketss</p>
</div>

<div class="imagen-principal">
    <img src="./css/super.png" />
</div>

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication8.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EL GRAN SUPERMARKET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supermercado" asp-action="Crear">Supermercado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supermercado" asp-action="Index">Lista de Supermercados</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Supermercado/Crear.cshtml
@model Supermercado

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Supermercado
    </div>
    <div class="card-body">
        <form method="post" asp-controller="Supermercado" asp-action="Crear" class="form-group">

            <div class="mb-3">
                <label class="form-label">Nombre Supermercado</label>
                <input asp-for="NameSuper" type="text" class="form-control">
            </div>

            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="Direccion" type="text" class="form-control">
            </div>

            <div class="mb-3">
                <label class="form-label">Autoservicio</label>
                <input asp-for="Autoservicio" type="text" class="form-control">
            </div>

            <button type="submit" class="btn btn-primary">Crear</button>
          
        </form>
    </div>
</div>

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Supermercado/Index.cshtml
@using WebApplication8.Models;
@model List<Supermercado>


@{
    ViewData["title"] = "Index";
}

@if (Model.Count != 0)
{
    <table class="table table-info" method="post" asp-action="Modificar" asp-controller="Supermercado">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">NameSuper</th>
                <th scope="col">Direccion</th>
                <th scope="col">Autoservicio</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var super in Model)
            {
                <tr>
                    <td>@super.Id</td>
                    <td>@super.NameSuper</td>
                    <td>@super.Direccion</td>
                    <td>@super.Autoservicio</td>
                </tr>
            }
        </tbody>

    </table>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-2 offset-sm-2 ">
                <input type="submit" value="Crear" class="btn btn-primary form-control" />
            </div>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary" onclick="Index">Editar</button>
            </div>
        </div>
    </div>

}
else
{
    <div class="card">
        <div class="card-body">
            No hay datos.
        </div>
    </div>
}

ASP.NET.PROYECTO FINAL/8.Aplicacion Web/WebApplication8/WebApplication8/Views/Supermercado/Modificar.cshtml
@using WebApplication8.Models;
@model List<Supermercado>

@{
    ViewData["Title"] = "Modificar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Count != 0)
{
    <table class="table table-info">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">NameSuper</th>
                <th scope="col">Direccion</th>
                <th scope="col">Autoservicio</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var super in Model)
            {
                <tr>
                    <td>@super.Id</td>
                    <td>@super.NameSuper</td>
                    <td>@super.Direccion</td>
                    <td>@super.Autoservicio</td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    <div class="card">
        <div class="card-body">
            No hay datos.
        </div>
    </div>
}